name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:

jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo " '${{ github.event_name }}' triggered the event."
          echo " Workfow is running on branch ${{ github.ref }} of the repo."

      - uses: actions/checkout@v4.1.1

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    needs: Build
    environment: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ..."
      
  Load-Test:
    needs: Build
    environment: Load-Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing ..." && sleep 15s

  Production: 
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - run: echo "Step 1 deploying..." && sleep 10s
      - run: echo "Step 2 deploying..." && sleep 10s
      - run: echo "Step 3 deploying..." && sleep 10s
      - run: echo "Step 4 deploying..." && sleep 10s
      - run: echo "Step 5 deploying..." && sleep 10s
    
